2023-05-15 16:41:29.479 +08:00 [INF] Starting Hangfire Server using job storage: 'In-Memory Storage'
2023-05-15 16:41:29.499 +08:00 [INF] Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2023-05-15 16:41:29.510 +08:00 [INF] Server chbeilt0062:7552:49da2a95 successfully announced in 1.2725 ms
2023-05-15 16:41:29.513 +08:00 [INF] Server chbeilt0062:7552:49da2a95 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, Worker, DelayedJobScheduler, RecurringJobScheduler...
2023-05-15 16:41:29.520 +08:00 [INF] Server chbeilt0062:7552:49da2a95 all the dispatchers started
2023-05-15 16:41:35.677 +08:00 [WRN] Failed to process the job 'c21c2c01-3905-4ea0-8ade-434e4143969c': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:34.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 13
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:41:39.010 +08:00 [WRN] Failed to process the job '0cc2b4e7-9a89-42be-8ab3-d0a236e8548e': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:24.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 13
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 10
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:41:42.431 +08:00 [WRN] Failed to process the job '253d5509-8f5e-49d8-a309-490dde06ca40': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:35.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 13
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 10
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:41:58.253 +08:00 [INF] Server chbeilt0062:7552:49da2a95 caught stopping signal...
2023-05-15 16:41:58.255 +08:00 [INF] Server chbeilt0062:7552:49da2a95 All dispatchers stopped
2023-05-15 16:41:58.257 +08:00 [INF] Server chbeilt0062:7552:49da2a95 successfully reported itself as stopped in 0.3121 ms
2023-05-15 16:41:58.257 +08:00 [INF] Server chbeilt0062:7552:49da2a95 has been stopped in total 3.5047 ms
2023-05-15 16:43:03.687 +08:00 [INF] Starting Hangfire Server using job storage: 'In-Memory Storage'
2023-05-15 16:43:03.704 +08:00 [INF] Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2023-05-15 16:43:03.716 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 successfully announced in 1.6309 ms
2023-05-15 16:43:03.717 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, Worker, DelayedJobScheduler, RecurringJobScheduler...
2023-05-15 16:43:03.724 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 all the dispatchers started
2023-05-15 16:43:07.514 +08:00 [WRN] Failed to process the job 'e4f60898-99b4-4a7b-a131-8c4b27cbfb92': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:37.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:43:09.480 +08:00 [WRN] Failed to process the job 'f713de64-90f9-4d52-bf0a-872d6edff0fd': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:19.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:43:17.832 +08:00 [WRN] Failed to process the job '473e70b6-57c5-4e09-9f22-42f804dab8c8': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:34.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:43:33.753 +08:00 [WRN] Failed to process the job 'f713de64-90f9-4d52-bf0a-872d6edff0fd': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:36.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:43:47.485 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 caught stopping signal...
2023-05-15 16:43:47.487 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 All dispatchers stopped
2023-05-15 16:43:47.488 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 successfully reported itself as stopped in 0.2494 ms
2023-05-15 16:43:47.488 +08:00 [INF] Server chbeilt0062:98128:f439a7b5 has been stopped in total 2.2326 ms
2023-05-15 16:44:07.721 +08:00 [INF] Starting Hangfire Server using job storage: 'In-Memory Storage'
2023-05-15 16:44:07.738 +08:00 [INF] Using the following options for Hangfire Server:
    Worker count: 20
    Listening queues: 'default'
    Shutdown timeout: 00:00:15
    Schedule polling interval: 00:00:15
2023-05-15 16:44:07.747 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c successfully announced in 1.2337 ms
2023-05-15 16:44:07.749 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, Worker, DelayedJobScheduler, RecurringJobScheduler...
2023-05-15 16:44:07.755 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c all the dispatchers started
2023-05-15 16:44:11.353 +08:00 [WRN] Failed to process the job '2f93367e-63ea-4bca-8a46-378e35300df3': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:26.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:11.353 +08:00 [WRN] Failed to process the job 'e2fbe24c-966a-4369-94f8-4f4760586f91': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:19.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:16.935 +08:00 [WRN] Failed to process the job '3e286ad5-052e-49a1-9ba5-5b473038fbc2': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:19.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:16.935 +08:00 [WRN] Failed to process the job 'ea8e5c61-1c5a-4598-9f96-71dcf3afa981': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:28.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:24.680 +08:00 [WRN] Failed to process the job 'b8af7fb8-cee8-4eec-8e13-fe58a777ebe1': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:24.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:24.680 +08:00 [WRN] Failed to process the job 'a947c277-2f02-4f0d-a8d6-70e96245653c': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:18.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:28.089 +08:00 [WRN] Failed to process the job 'aa350381-dc11-4e0e-a6de-c818c8ccdd98': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:20.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:31.151 +08:00 [WRN] Failed to process the job 'e5b625a9-ad62-4119-8dbc-450a9222edba': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:16.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:37.786 +08:00 [WRN] Failed to process the job 'e2fbe24c-966a-4369-94f8-4f4760586f91': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:22.
System.Exception: DemoJob failed
   at Jobs.Schedules.DemoJob.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.DemoJob.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\DemoJob.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:37.786 +08:00 [WRN] Failed to process the job '3e286ad5-052e-49a1-9ba5-5b473038fbc2': an exception occurred. Retry attempt 2 of 10 will be performed in 00:01:14.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:37.786 +08:00 [WRN] Failed to process the job '2f93367e-63ea-4bca-8a46-378e35300df3': an exception occurred. Retry attempt 2 of 10 will be performed in 00:00:58.
System.Exception: DemoJob failed
   at Jobs.Schedules.Demo2Job.<Execute>b__2_0() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 11
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Jobs.Schedules.Demo2Job.Execute() in C:\Users\1035693.QUEST-GLOBAL\Desktop\Projects\Malfurion\Malfurion.Solution\Web\General\Jobs\Schedules\Demo2Job.cs:line 8
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2023-05-15 16:44:46.086 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c caught stopping signal...
2023-05-15 16:44:46.087 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c All dispatchers stopped
2023-05-15 16:44:46.089 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c successfully reported itself as stopped in 0.2145 ms
2023-05-15 16:44:46.089 +08:00 [INF] Server chbeilt0062:83052:1c65ce6c has been stopped in total 2.641 ms
